### ISSUE TITLE
on build "Unable to find template file"

### ISSUE THREAD

**Issue by Sillkix** [vituum/vite-plugin-twig#1]
I am currently experiencing the issue, that when i am build the project i get the following error message if i extend or include an other twig file:
`TwigException: Unable to find template file D:\Projects\Vituum\src\views\layout\_base.twig. Error: ENOENT: no such file or directory, stat 'D:\Projects\Vituum\src\views\layout\_base.twig`
If i run 'vite dev' it works without a problem. And it is the correct path. I think it is because the files get renamed for a short moment while building.

folder structure:
![grafik](https://user-images.githubusercontent.com/68162660/213281271-adee4147-c726-4c15-aa8d-1d0f84f57b1b.png)

_base.twig
![grafik](https://user-images.githubusercontent.com/68162660/213281443-ea1acc1e-60a2-4af4-af06-e11f046f7c20.png)

index.twig
![grafik](https://user-images.githubusercontent.com/68162660/213281541-056ae77e-0c20-42ea-bf7c-6e41d31cd8c2.png)

package.json
![grafik](https://user-images.githubusercontent.com/68162660/213281918-5ec389a9-33c8-4154-a40d-b03448ead716.png)

vite.config.js
![grafik](https://user-images.githubusercontent.com/68162660/213281962-4a4cc2e6-297a-4bb6-bfab-cf7a70c0d83d.png)

**Comment by lubomirblazekcz** [comment]
Views dir should be used only for entry page files, actual templates should be located somewhere else, like templates dir.

See example here - https://stackblitz.com/github/vituum/vituum/tree/main/examples/twig?file=src%2Fviews%2Fhello.twig

**Comment by Enovate-Jordan** [comment]
Hi @lubomirblazekcz,

Sorry to revive this but I'm at a loss here. I'm consitently getting the same error when trying to import my macros.twig file within the components file directory. This site primarily a laravel/blade app, however we have a section of the app which is pulling in data externally from a craft cms site, we decided to build that section in twig. I recently migrated the site from mix to vite, which prompted me to try out your plugin.


vite.config.js
```js
import vituum from 'vituum'
import twig from '@vituum/vite-plugin-twig';
...

    plugins: [
        vituum(),
        twig(),
        ...
    ],
    
    ....
    
        build: {
        rollupOptions: {
            input: [
                'resources/views/twig-section/*/*.twig',
            ],
        }
    },

```

Import statement:
```twig
{% import "resources/views/twig-section/components/macros.twig" as macros %}
```

Error:
```bash
[vite:build-html] Unable to find template file /Users/name/Sites/project/resources/views/twig-section/components/macros.twig. Error: ENOENT: no such file or directory, stat '/Users/name/Sites/project/resources/views/twig-section/components/macros.twig'
```

Directory Screenshot:
<img width="1106" alt="Screenshot 2024-02-22 at 17 25 21" src="https://github.com/vituum/vite-plugin-twig/assets/107923440/276073d5-27af-4a22-b09b-a5457bc89457">

**Comment by lubomirblazekcz** [comment]
Can you provide a reproduction on stackblitz? I can take a look and help
