### ISSUE TITLE
Import Twig in the JS

### ISSUE THREAD

**Issue by ay13** [vituum/vite-plugin-twig#3]
Is it possible to use this plugin to import the twig file in the JS?

Example: https://stackblitz.com/edit/vitejs-vite-lsxomt?file=main.js

I get an error that says 

> Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .twig file format, or if it's an asset, add "**/*.twig" to `assetsInclude` in your configuration.

My end goal is to import twig into Storybook using Vite loader I can set up an example of this if needed. I can use https://github.com/zimmo-be/twig-loader for the webpack loader but I would like to switch over to Vite.

Thanks.

**Comment by lubomirblazekcz** [comment]
The plugin currently supports only importing twig files in html, not in js. But it should be doable via vite plugin api, eg.

```javascript
const fileRegex = /\.(twig)$/

function myPlugin() {
    return {
        name: 'transform-file',

        transform(twigFileContent, path) {
            if (fileRegex.test(path)) {
                // do twig transform here - https://github.com/vituum/vite-plugin-twig/blob/main/index.js#L114
                twigFileContent = 'export default "haahaha"'
                return {
                    code: twigFileContent,
                    map: null, // provide source map if available
                }
            }
        },
    }
}

export default {
    plugins: [
        myPlugin()
    ],
    assetsInclude: ['**/*.twig']
}
```

And in `main.js`
```javascript
import twigTemplate from './file.twig'

console.log(twigTemplate)
```
